NAME = 'name'
PASSWORD = 'password'
RESPONSE = 'response'
SESSION_ID = 'session_id'
USER_ID = 'user_id'
FILE_NAME = 'file_name'
FILE_CHUNK = 'file_chunk'

SIGNUP = 'signup'
LOGIN = 'login'
LOGOUT = 'logout'
HISTORY = 'history'
LISTING = 'listing'
DOWNLOAD = 'download'
UPLOAD = 'upload'
SEARCH = 'search'
